S0 () {
  AddGlobalParam "commit" 42
  AbortFail echo "IO ${sid}"
  AbortFail sleep 3
}

S1 () {
  AbortFail echo "I1 -$*-"
  AbortFail sleep 1
  #AbortFail curl http://www.a.b
}

S2 () {
  AbortFail echo "S2 $1 $commit ${rankid}"
  AbortFail sleep 3
}

S2a () {
  AbortFail echo "S2a $1"
  AbortFail sleep 5
}

S3 () {
  AbortFail echo "S3 $commit"
  AbortFail sleep 1
}

CleanupUser () {
  echo "CLEAN"
}

EXECUTION="S0; S1 p1; S2 42 || S2 69 || S2a 123 456 789; S3"

