Init () {
  AbortFail test -n "$1" || return 1;
  AddGlobalParam "commit" $1
  shift
  AbortFail test -n "$*" || return 1;
  AddGlobalParam "cmds" "$*"
}

GitCheckout () {
  #AbortFail git clone https://github.com/tlspuffin/tlspuffin.git git.${sid} || return 1;
  AbortFail cp -apr source.git git.${sid} || return 1;
  AbortFail cd git.${sid} || return 1;
  AbortFail git checkout $commit || return 1;
}

RunTest () {
  AbortFail cd git.${sid} || return 1;
  AbortFail timeout 60m nix-shell --run "${cmds}" || return 1;
}

CleanupUser () {
  rm -rf git.${sid}
}

EXECUTION="Init $*; GitCheckout; RunTest"
