Init () {
  echo "################ Init ################" >&2;
  commit=${COMMIT_ID}
  shift
  [ -z "${commit}" ] && commit="main"
  #AddGlobalParam "COMMIT_ID" ${commit}

  AddGlobalParam "START_PORT" $(( 6000 ))

  #AbortFail git clone https://github.com/tlspuffin/tlspuffin.git ${COMMONPATH}/repo || return 1;
  AbortFail cp -apr ${OUTPATH}/../../repo ${COMMONPATH}/repo || return 1;
  AbortFail cd ${COMMONPATH}/repo || return 1;
  AbortFail git checkout "${commit}" || return 1;
  AbortFail git submodule update --init --recursive || return 1;

  AbortFail cp ${INPATH}/shell.nix . || return 1
  AbortFail nix-shell --run cargo >/dev/null 2>/dev/null || return 1;

  return 0;
}

Build() {
  shift;
  features=$1;

  [ -z "${COMMIT_ID}" ] && return 1;
  echo "tlspuffin-${COMMIT_ID}-${features}"
  MD5SUM_RES=$( echo "tlspuffin-${COMMIT_ID}-${features}" | md5sum )
  CACHE_ID="tlspuffin-${MD5SUM_RES%% *}"
  echo "cid: ${CACHE_ID}"
  cache_ok=1
  if [[ "${COMMIT_ID}" != "main" ]]; then
    binary=$( ${TOOLSPATH}/get_file.sh -q "$CACHE_ID" )
    cache_ok=$?
  fi
  if [[ $cache_ok -ne 0 ]]; then
    AbortFail cp -apr ${COMMONPATH}/repo . || return 1;
    AbortFail cd repo || return 1;
    AbortFail cp ${INPATH}/shell.nix . || return 1
    AbortFail nix-shell --run "cargo build --bin tlspuffin --release --features=${features}" || return 1;
    binary=$( realpath ./target/release/tlspuffin )
    AbortFail curl -s -X POST "http://localhost:8080/api/cache_put" -F "id=$CACHE_ID" -F "path=${binary}" || return 1;
  fi

  AbortFail cp "${binary}" "${COMMONPATH}/" || return 1;
  #CreateArtefact "${binary}" "${CACHE_ID}" "commit_id:${COMMIT_ID}" "is_release:true"

  return 0
}

Experiment () {
  experiment=$1
  features=$2
  additional_args=$3
  MD5SUM_RES=$( echo "tlspuffin-${COMMIT_ID}-${features}" | md5sum )
  binary="${COMMONPATH}/tlspuffin-${MD5SUM_RES%% *}"

  #core=${CORES%%,*}
  core=0
  #end_core=${CORES##*,}
  end_core=$(( NBCORES - 1))
  port=$(( START_PORT + RUN_ID ))

  AbortFail cp ${INPATH}/shell.nix . || return 1
  AbortFail nix-shell --run "\"${binary}\" seed" || return 1;
  #echo nix-shell --run "\"${binary}\" --cores \"${core}-${end_core}\" --port \"${port}\" ${additional_args} experiment -d \"${experiment}\" -t \"${experiment}\""
  nix-shell --run "\"${binary}\" --cores \"${core}-${end_core}\" --port \"${port}\" ${additional_args} experiment -d \"${experiment}\" -t \"${experiment}\"" &
  TLSPUFFIN_PID=$!

  sleep 10
  kill -0 ${TLSPUFFIN_PID} 2>/dev/null
  if (( $? == 0 )); then
    TLSPUFFIN_OUTPATH=$( ls experiments/ )
    CreateArtefact "./experiments/${TLSPUFFIN_OUTPATH}/README.md" "${STEP_NAME}/${ATTEMPT_ID}-README.md" "commit_id:${COMMIT_ID}" "features:${features}"
    CreateArtefact "./experiments/${TLSPUFFIN_OUTPATH}/stats.json" "${STEP_NAME}/${ATTEMPT_ID}-stats.json" "commit_id:${COMMIT_ID}" "features:${features}"
  fi

  CRASHED=0
  while true; do
    sleep 10
    kill -0 ${TLSPUFFIN_PID} 2>/dev/null
    if (( $? != 0 )); then
      CRASHED=1
      break;
    fi
    OBJ_COUNT=$( find experiments/*/objective -maxdepth 1 -type f -name '*.trace' 2>/dev/null | wc -l )
    if (( ${OBJ_COUNT} > 0 )); then
      kill -15 ${TLSPUFFIN_PID} 2> /dev/null
      N=10
      for (( i=0; i<N; i++ )); do
        kill -0 ${TLSPUFFIN_PID} 2> /dev/null
        if (( $? != 0 )); then
          break;
        fi
      done
      kill -0 ${TLSPUFFIN_PID} 2> /dev/null
      if (( $? == 0 )); then
        sleep 5
        kill -9 ${TLSPUFFIN_PID} 2> /dev/null
      fi
      break;
    fi
  done
  wait "$TLSPUFFIN_PID" 2>/dev/null

  return ${CRASHED}
}

ManageResults () {
  python3 /home/olivier/Desktop/Exec/scripts/reports_generate/cli.py generate --commit ${COMMIT_ID} ${OUTPATH}/artefacts out.csv
  python3 /home/olivier/Desktop/Exec/scripts/reports_generate/cli.py report --outdir out out.csv
  CreateArtefact "./out/report" "report" "commit_id:${COMMIT_ID}"
  return 0
}

CleanupUser () {
  echo "CLEAN"
  echo rm -rf git.${sid}
}
