Init () {
  echo "################ Init ################" >&2;
  if [ -z "$1" ]; then
    echo "Fail: Illegal number of parameters" >&2;
    return 1;
  fi
  AddGlobalParam "START_CORE" 0
  AddGlobalParam "CORES_PER_EXPERIMENT" $(( $1 ))
  AddGlobalParam "START_PORT" $(( 6000 ))
  shift
  commit="$1"
  [ -z "${commit}" ] && commit="main"
  #AbortFail git clone https://github.com/tlspuffin/tlspuffin.git git.${sid} || return 1;
  AbortFail echo cp -apr source.git git.${sid} || return 1;
  cd git.${sid}
  AbortFail echo git checkout "${commit}" || return 1;
}

Experiment () {
  experiment=$1
  features=$2
  additional_args=$3
  binary="target/release/tlspuffin"

  core=$(( START_CORE + ( rankid * CORES_PER_EXPERIMENT ) ))
  end_core=$(( core + CORES_PER_EXPERIMENT - 1 ))
  port=$(( START_PORT + rankid ))

  AbortFail echo cp -apr "git.${sid}" "git.${sid}.${rankid}" || return 1
  AbortFail echo cd "git.${sid}.${rankid}" || return 1
  #cd git.251113.0

  AbortFail echo nix-shell --run "cargo build --bin tlspuffin --release --features=\"${features}\"" || return 1;
  AbortFail echo nix-shell --run "\"${binary}\" seed" || return 1;
  AbortFail echo nix-shell --run "\"${binary}\" --cores \"${core}-${end_core}\" --port \"${port}\" ${additional_args} experiment -d \"${experiment}\" -t \"${experiment}\"" || return 1;
}

CleanupUser () {
  echo "CLEAN"
  echo rm -rf git.${sid}
}

EXECUTION="Init $*; Experiment 'SDOS2' 'wolfssl540,asan,wolfssl-disable-postauth,fix-CVE-2022-39173' '--put-use-clear' || \
  Experiment 'SDOS1' 'openssl111j' || Experiment 'HEAP' 'wolfssl540,asan,fix-CVE-2022-39173'"
#EXECUTION="Init $*; Experiment 'SDOS2' 'wolfssl540,asan,wolfssl-disable-postauth,fix-CVE-2022-39173' '--put-use-clear'" 
