#!/bin/bash


cd "$( dirname $( realpath "${BASH_SOURCE[0]}" ) )"

# the expected bug of each VulnA/VulnB preset (data/html/jobsscripts/tlspuffin/vuln_targets.json), as a shell table
# of the job scripts: vendor -> "cve|kind|match"; and the claims set apart (_not_targeted)
targets=../data/html/jobsscripts/tlspuffin/vuln_targets.json
{
  echo '# generated by build.sh from vuln_targets.json'
  echo 'declare -gA VULN_TARGETS=('
  jq -r 'to_entries[] | select(.key | startswith("_") | not) | "  [\(.key | @sh)]=\("\(.value.cve)|\(.value.kind)|\(.value.match)" | @sh)"' "${targets}"
  echo ')'
  # the claims set apart (never a target): claim -> CVE
  echo 'declare -gA OBJECTIVES_NOT_TARGETED=('
  jq -r '._not_targeted // {} | to_entries[] | "  [\(.key | @sh)]=\("\(.value.cve)|\(.value.library // "")|\(.value.below // "")" | @sh)"' "${targets}"
  echo ')'
} > PR_targets.sh || exit 1

# the puffin-bench commit of these job scripts, recorded by each run (SummaryAddBench: bench.jobscripts), so that a
# hot copy of the scripts (without a deploy of the services) is told apart; dirty: local changes in the scripts
commit=$( git rev-parse HEAD 2> /dev/null || echo unknown )
dirty=false
# (the QuickJS scripts of data/tools run with the job scripts: they count too)
[ -n "$( git status --porcelain -- . ../data/html/jobsscripts ../data/tools 2> /dev/null )" ] && dirty=true
printf '# puffin-bench version of these job scripts (generated by build.sh)\nPB_JOBSCRIPTS_COMMIT=%q\nPB_JOBSCRIPTS_DATE=%q\nPB_JOBSCRIPTS_DIRTY=%q\n' \
    "${commit}" "$( git log -1 --format=%cs 2> /dev/null )" "${dirty}" > PR_version.sh

cat PR_version.sh PR_common.sh PR_compat.sh PR_targets.sh PR_perf.sh > PR_perf_full.sh
cat PR_version.sh PR_common.sh PR_compat.sh PR_targets.sh PR_vulnerabilities.sh > PR_vulnerabilities_full.sh

echo "All done in $( pwd )"

